services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8000"  # Octane läuft auf Port 8000
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
            - redis

    mysql:
        image: mysql:8.0
        ports:
            - "3307:3306"
        environment:
            - MYSQL_DATABASE=bfr
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - mysql-data:/var/lib/mysql

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data

volumes:
    mysql-data:
    redis-data:
