<?php

namespace Database\Seeders\Address;

use App\Models\Address\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['id' => 1, 'code' => 'CH','name' => 'Schweiz', 'currency' => 'CHF', 'phonecode' => +41],
            ['id' => 2, 'code' => 'DE','name' => 'Deutschland', 'currency' => 'EUR', 'phonecode' => +49],
            ['id' => 3, 'code' => 'AT','name' => 'Österreich', 'currency' => 'EUR', 'phonecode' => +43],
            ['id' => 4, 'code' => 'LI','name' => 'Liechtenstein', 'currency' => 'CHF', 'phonecode' => +423],
            ['id' => 5, 'code' => 'IT','name' => 'Italien', 'currency' => 'EUR', 'phonecode' => +39],
            ['id' => 6, 'code' => 'FR','name' => 'Frankreich', 'currency' => 'EUR', 'phonecode' => +33],
            ['id' => 7, 'code' => 'ES','name' => 'Spanien', 'currency' => 'EUR', 'phonecode' => +34],

            ['id' => 8, 'code' => 'AD','name' => 'Andorra', 'currency' => 'EUR', 'phonecode' => +376],
            ['id' => 9, 'code' => 'AL','name' => 'Albanien', 'currency' => 'ALL', 'phonecode' => +355],
            ['id' => 10, 'code' => 'BE','name' => 'Belgien', 'currency' => 'EUR', 'phonecode' => +32],
            ['id' => 11, 'code' => 'BG','name' => 'Bulgarien', 'currency' => 'BGN', 'phonecode' => +359],
            ['id' => 12, 'code' => 'BY','name' => 'Weißrussland', 'currency' => 'BYN', 'phonecode' => +375],
            ['id' => 13, 'code' => 'CZ','name' => 'Tschechische Republik', 'currency' => 'CZK', 'phonecode' => +420],
            ['id' => 14, 'code' => 'CY','name' => 'Zypern', 'currency' => 'EUR', 'phonecode' => +357],
            ['id' => 15, 'code' => 'DK','name' => 'Dänemark', 'currency' => 'DKK', 'phonecode' => +45],
            ['id' => 16, 'code' => 'EE','name' => 'Estland', 'currency' => 'EUR', 'phonecode' => +372],
            ['id' => 17, 'code' => 'FO','name' => 'Färöer Inseln', 'currency' => 'DKK', 'phonecode' => +298],
            ['id' => 18, 'code' => 'FI','name' => 'Finnland', 'currency' => 'EUR', 'phonecode' => +358],
            ['id' => 19, 'code' => 'GR','name' => 'Griechenland', 'currency' => 'EUR', 'phonecode' => +30],
            ['id' => 20, 'code' => 'HU','name' => 'Ungarn', 'currency' => 'HUF', 'phonecode' => +36],
            ['id' => 21, 'code' => 'IS','name' => 'Island', 'currency' => 'ISK', 'phonecode' => +354],
            ['id' => 22, 'code' => 'IE','name' => 'Irland', 'currency' => 'EUR', 'phonecode' => +353],
            ['id' => 23, 'code' => 'LV','name' => 'Lettland', 'currency' => 'EUR', 'phonecode' => +371],
            ['id' => 24, 'code' => 'LT','name' => 'Litauen', 'currency' => 'EUR', 'phonecode' => +370],
            ['id' => 25, 'code' => 'LU','name' => 'Luxemburg', 'currency' => 'EUR', 'phonecode' => +352],
            ['id' => 26, 'code' => 'MT','name' => 'Malta', 'currency' => 'EUR', 'phonecode' => +356],
            ['id' => 27, 'code' => 'MD','name' => 'Moldawien', 'currency' => 'MDL', 'phonecode' => +373],
            ['id' => 28, 'code' => 'MC','name' => 'Monaco', 'currency' => 'EUR', 'phonecode' => +377],
            ['id' => 29, 'code' => 'ME','name' => 'Montenegro', 'currency' => 'EUR', 'phonecode' => +382],
            ['id' => 30, 'code' => 'NL','name' => 'Niederlande', 'currency' => 'EUR', 'phonecode' => +31],
            ['id' => 31, 'code' => 'NO','name' => 'Norwegen', 'currency' => 'NOK', 'phonecode' => +47],
            ['id' => 32, 'code' => 'PL','name' => 'Polen', 'currency' => 'PLN', 'phonecode' => +48],
            ['id' => 33, 'code' => 'PT','name' => 'Portugal', 'currency' => 'EUR', 'phonecode' => +351],
            ['id' => 34, 'code' => 'RO','name' => 'Rumänien', 'currency' => 'RON', 'phonecode' => +40],
            ['id' => 35, 'code' => 'RU','name' => 'Russland', 'currency' => 'RUB', 'phonecode' => +7],
            ['id' => 36, 'code' => 'SM','name' => 'San Marino', 'currency' => 'EUR', 'phonecode' => +378],
            ['id' => 37, 'code' => 'RS','name' => 'Serbien', 'currency' => 'RSD', 'phonecode' => +381],
            ['id' => 38, 'code' => 'SK','name' => 'Slowakei', 'currency' => 'EUR', 'phonecode' => +421],
            ['id' => 39, 'code' => 'SI','name' => 'Slowenien', 'currency' => 'EUR', 'phonecode' => +386],
            ['id' => 40, 'code' => 'SE','name' => 'Schweden', 'currency' => 'SEK', 'phonecode' => +46],
            ['id' => 41, 'code' => 'UA','name' => 'Ukraine', 'currency' => 'UAH', 'phonecode' => +380],
            ['id' => 42, 'code' => 'GB','name' => 'United Kingdom', 'currency' => 'GBP', 'phonecode' => +44],
            ['id' => 43, 'code' => 'XK','name' => 'Kosovo', 'currency' => 'EUR', 'phonecode' => +383],

            // Nordamerika
            ['id' => 44, 'code' => 'US','name' => 'USA', 'currency' => 'USD', 'phonecode' => '+1'],
            ['id' => 45, 'code' => 'CA','name' => 'Kanada', 'currency' => 'CAD', 'phonecode' => '+1'],
            ['id' => 46, 'code' => 'MX','name' => 'Mexiko', 'currency' => 'MXN', 'phonecode' => '+52'],

            // Mittelamerika
            ['id' => 47, 'code' => 'BZ','name' => 'Belize', 'currency' => 'BZD', 'phonecode' => '+501'],
            ['id' => 48, 'code' => 'CR','name' => 'Costa Rica', 'currency' => 'CRC', 'phonecode' => '+506'],
            ['id' => 49, 'code' => 'SV','name' => 'El Salvador', 'currency' => 'USD', 'phonecode' => '+503'],
            ['id' => 50, 'code' => 'GT','name' => 'Guatemala', 'currency' => 'GTQ', 'phonecode' => '+502'],
            ['id' => 51, 'code' => 'HN','name' => 'Honduras', 'currency' => 'HNL', 'phonecode' => '+504'],
            ['id' => 52, 'code' => 'NI','name' => 'Nicaragua', 'currency' => 'NIO', 'phonecode' => '+505'],
            ['id' => 53, 'code' => 'PA','name' => 'Panama', 'currency' => 'PAB', 'phonecode' => '+507'],

            // Südamerika
            ['id' => 54, 'code' => 'AR','name' => 'Argentinien', 'currency' => 'ARS', 'phonecode' => '+54'],
            ['id' => 55, 'code' => 'BO','name' => 'Bolivien', 'currency' => 'BOB', 'phonecode' => '+591'],
            ['id' => 56, 'code' => 'BR','name' => 'Brasilien', 'currency' => 'BRL', 'phonecode' => '+55'],
            ['id' => 57, 'code' => 'CL','name' => 'Chile', 'currency' => 'CLP', 'phonecode' => '+56'],
            ['id' => 58, 'code' => 'CO','name' => 'Kolumbien', 'currency' => 'COP', 'phonecode' => '+57'],
            ['id' => 59, 'code' => 'EC','name' => 'Ecuador', 'currency' => 'USD', 'phonecode' => '+593'],
            ['id' => 60, 'code' => 'GY','name' => 'Guyana', 'currency' => 'GYD', 'phonecode' => '+592'],
            ['id' => 61, 'code' => 'PY','name' => 'Paraguay', 'currency' => 'PYG', 'phonecode' => '+595'],
            ['id' => 62, 'code' => 'PE','name' => 'Peru', 'currency' => 'PEN', 'phonecode' => '+51'],
            ['id' => 63, 'code' => 'SR','name' => 'Suriname', 'currency' => 'SRD', 'phonecode' => '+597'],
            ['id' => 64, 'code' => 'UY','name' => 'Uruguay', 'currency' => 'UYU', 'phonecode' => '+598'],
            ['id' => 65, 'code' => 'VE','name' => 'Venezuela', 'currency' => 'VES', 'phonecode' => '+58'],

            // Mittlerer Osten
            ['id' => 66, 'code' => 'AE','name' => 'Vereinigte Arabische Emirate', 'currency' => 'AED', 'phonecode' => '+971'],
            ['id' => 67, 'code' => 'AM','name' => 'Armenien', 'currency' => 'AMD', 'phonecode' => '+374'],
            ['id' => 68, 'code' => 'AZ','name' => 'Aserbaidschan', 'currency' => 'AZN', 'phonecode' => '+994'],
            ['id' => 69, 'code' => 'BH','name' => 'Bahrain', 'currency' => 'BHD', 'phonecode' => '+973'],
//            ['id' => 70, 'code' => 'CY','name' => 'Zypern', 'currency' => 'EUR', 'phonecode' => '+357'],
            ['id' => 71, 'code' => 'GE','name' => 'Georgien', 'currency' => 'GEL', 'phonecode' => '+995'],
            ['id' => 72, 'code' => 'IQ','name' => 'Irak', 'currency' => 'IQD', 'phonecode' => '+964'],
            ['id' => 73, 'code' => 'IR','name' => 'Iran', 'currency' => 'IRR', 'phonecode' => '+98'],
            ['id' => 74, 'code' => 'IL','name' => 'Israel', 'currency' => 'ILS', 'phonecode' => '+972'],
            ['id' => 75, 'code' => 'JO','name' => 'Jordanien', 'currency' => 'JOD', 'phonecode' => '+962'],
            ['id' => 76, 'code' => 'KW','name' => 'Kuwait', 'currency' => 'KWD', 'phonecode' => '+965'],
            ['id' => 77, 'code' => 'LB','name' => 'Libanon', 'currency' => 'LBP', 'phonecode' => '+961'],
            ['id' => 78, 'code' => 'OM','name' => 'Oman', 'currency' => 'OMR', 'phonecode' => '+968'],
            ['id' => 79, 'code' => 'QA','name' => 'Katar', 'currency' => 'QAR', 'phonecode' => '+974'],
            ['id' => 80, 'code' => 'SA','name' => 'Saudi-Arabien', 'currency' => 'SAR', 'phonecode' => '+966'],
            ['id' => 81, 'code' => 'SY','name' => 'Syrien', 'currency' => 'SYP', 'phonecode' => '+963'],
            ['id' => 82, 'code' => 'TR','name' => 'Türkei', 'currency' => 'TRY', 'phonecode' => '+90'],
            ['id' => 83, 'code' => 'YE','name' => 'Jemen', 'currency' => 'YER', 'phonecode' => '+967'],

            //Afrika
            ['id' => 84, 'code' => 'DZ','name' => 'Algerien', 'currency' => 'DZD', 'phonecode' => '+213'],
            ['id' => 85, 'code' => 'AO','name' => 'Angola', 'currency' => 'AOA', 'phonecode' => '+244'],
            ['id' => 86, 'code' => 'BJ','name' => 'Benin', 'currency' => 'XOF', 'phonecode' => '+229'],
            ['id' => 87, 'code' => 'BW','name' => 'Botswana', 'currency' => 'BWP', 'phonecode' => '+267'],
            ['id' => 88, 'code' => 'BF','name' => 'Burkina Faso', 'currency' => 'XOF', 'phonecode' => '+226'],
            ['id' => 89, 'code' => 'BI','name' => 'Burundi', 'currency' => 'BIF', 'phonecode' => '+257'],
            ['id' => 90, 'code' => 'CV','name' => 'Kap Verde', 'currency' => 'CVE', 'phonecode' => '+238'],
            ['id' => 91, 'code' => 'CM','name' => 'Kamerun', 'currency' => 'XAF', 'phonecode' => '+237'],
            ['id' => 92, 'code' => 'CF','name' => 'Zentralafrikanische Republik', 'currency' => 'XAF', 'phonecode' => '+236'],
            ['id' => 93, 'code' => 'TD','name' => 'Tschad', 'currency' => 'XAF', 'phonecode' => '+235'],
            ['id' => 94, 'code' => 'KM','name' => 'Komoren', 'currency' => 'KMF', 'phonecode' => '+269'],
            ['id' => 95, 'code' => 'CG','name' => 'Kongo-Brazzaville', 'currency' => 'XAF', 'phonecode' => '+242'],
            ['id' => 96, 'code' => 'CD','name' => 'Kongo-Kinshasa', 'currency' => 'CDF', 'phonecode' => '+243'],
            ['id' => 97, 'code' => 'CI','name' => 'Elfenbeinküste', 'currency' => 'XOF', 'phonecode' => '+225'],
            ['id' => 98, 'code' => 'DJ','name' => 'Dschibuti', 'currency' => 'DJF', 'phonecode' => '+253'],
            ['id' => 99, 'code' => 'EG','name' => 'Ägypten', 'currency' => 'EGP', 'phonecode' => '+20'],

            //Asia
            ['id' => 100, 'code' => 'AF','name' => 'Afghanistan', 'currency' => 'AFN', 'phonecode' => '+93'],
            ['id' => 101, 'code' => 'BD','name' => 'Bangladesch', 'currency' => 'BDT', 'phonecode' => '+880'],
            ['id' => 102, 'code' => 'BT','name' => 'Bhutan', 'currency' => 'BTN', 'phonecode' => '+975'],
            ['id' => 103, 'code' => 'BN','name' => 'Brunei', 'currency' => 'BND', 'phonecode' => '+673'],
            ['id' => 104, 'code' => 'KH','name' => 'Kambodscha', 'currency' => 'KHR', 'phonecode' => '+855'],
            ['id' => 105, 'code' => 'CN','name' => 'China', 'currency' => 'CNY', 'phonecode' => '+86'],
            ['id' => 106, 'code' => 'IN','name' => 'Indien', 'currency' => 'INR', 'phonecode' => '+91'],
            ['id' => 107, 'code' => 'ID','name' => 'Indonesien', 'currency' => 'IDR', 'phonecode' => '+62'],
            ['id' => 108, 'code' => 'JP','name' => 'Japan', 'currency' => 'JPY', 'phonecode' => '+81'],
            ['id' => 109, 'code' => 'KZ','name' => 'Kasachstan', 'currency' => 'KZT', 'phonecode' => '+7'],
            ['id' => 110, 'code' => 'KP','name' => 'Nordkorea', 'currency' => 'KPW', 'phonecode' => '+850'],
            ['id' => 111, 'code' => 'KR','name' => 'Südkorea', 'currency' => 'KRW', 'phonecode' => '+82'],
            ['id' => 112, 'code' => 'KG','name' => 'Kirgisistan', 'currency' => 'KGS', 'phonecode' => '+996'],
            ['id' => 113, 'code' => 'LA','name' => 'Laos', 'currency' => 'LAK', 'phonecode' => '+856'],
            ['id' => 114, 'code' => 'MY','name' => 'Malaysia', 'currency' => 'MYR', 'phonecode' => '+60'],
            ['id' => 115, 'code' => 'MV','name' => 'Malediven', 'currency' => 'MVR', 'phonecode' => '+960'],
            ['id' => 116, 'code' => 'MN','name' => 'Mongolei', 'currency' => 'MNT', 'phonecode' => '+976'],
            ['id' => 117, 'code' => 'MM','name' => 'Myanmar', 'currency' => 'MMK', 'phonecode' => '+95'],
            ['id' => 118, 'code' => 'NP','name' => 'Nepal', 'currency' => 'NPR', 'phonecode' => '+977'],
            ['id' => 119, 'code' => 'PK','name' => 'Pakistan', 'currency' => 'PKR', 'phonecode' => '+92'],
            ['id' => 120, 'code' => 'PH','name' => 'Philippinen', 'currency' => 'PHP', 'phonecode' => '+63'],
            ['id' => 121, 'code' => 'SG','name' => 'Singapur', 'currency' => 'SGD', 'phonecode' => '+65'],
            ['id' => 122, 'code' => 'LK','name' => 'Sri Lanka', 'currency' => 'LKR', 'phonecode' => '+94'],
            ['id' => 123, 'code' => 'TJ','name' => 'Tadschikistan', 'currency' => 'TJS', 'phonecode' => '+992'],
            ['id' => 124, 'code' => 'TH','name' => 'Thailand', 'currency' => 'THB', 'phonecode' => '+66'],
            ['id' => 125, 'code' => 'TM','name' => 'Turkmenistan', 'currency' => 'TMT', 'phonecode' => '+993'],
            ['id' => 126, 'code' => 'UZ','name' => 'Usbekistan', 'currency' => 'UZS', 'phonecode' => '+998'],
            ['id' => 127, 'code' => 'VN','name' => 'Vietnam', 'currency' => 'VND', 'phonecode' => '+84'],

            //Australien und Ozeanien

            ['id' => 128, 'code' => 'AU','name' => 'Australien', 'currency' => 'AUD', 'phonecode' => '+61'],
            ['id' => 129, 'code' => 'NZ','name' => 'Neuseeland', 'currency' => 'NZD', 'phonecode' => '+64'],
            ['id' => 130, 'code' => 'FJ','name' => 'Fidschi', 'currency' => 'FJD', 'phonecode' => '+679'],
            ['id' => 131, 'code' => 'PG','name' => 'Papua-Neuguinea', 'currency' => 'PGK', 'phonecode' => '+675'],
            ['id' => 132, 'code' => 'SB','name' => 'Salomonen', 'currency' => 'SBD', 'phonecode' => '+677'],
            ['id' => 133, 'code' => 'VU','name' => 'Vanuatu', 'currency' => 'VUV', 'phonecode' => '+678'],
            ['id' => 134, 'code' => 'NC','name' => 'Neukaledonien', 'currency' => 'XPF', 'phonecode' => '+687'],
            ['id' => 135, 'code' => 'PF','name' => 'Französisch-Polynesien', 'currency' => 'XPF', 'phonecode' => '+689'],
            ['id' => 136, 'code' => 'WS','name' => 'Samoa', 'currency' => 'WST', 'phonecode' => '+685'],
            ['id' => 137, 'code' => 'KI','name' => 'Kiribati', 'currency' => 'AUD', 'phonecode' => '+686'],
            ['id' => 138, 'code' => 'TO','name' => 'Tonga', 'currency' => 'TOP', 'phonecode' => '+676'],
            ['id' => 139, 'code' => 'FM','name' => 'Mikronesien', 'currency' => 'USD', 'phonecode' => '+691'],
            ['id' => 140, 'code' => 'MH','name' => 'Marshallinseln', 'currency' => 'USD', 'phonecode' => '+692'],
            ['id' => 141, 'code' => 'PW','name' => 'Palau', 'currency' => 'USD', 'phonecode' => '+680'],
            ['id' => 142, 'code' => 'NR','name' => 'Nauru', 'currency' => 'AUD', 'phonecode' => '+674'],
            ['id' => 143, 'code' => 'CK','name' => 'Cookinseln', 'currency' => 'NZD', 'phonecode' => '+682'],
            ['id' => 144, 'code' => 'TV','name' => 'Tuvalu', 'currency' => 'AUD', 'phonecode' => '+688'],
            ['id' => 145, 'code' => 'AS','name' => 'Amerikanisch-Samoa', 'currency' => 'USD', 'phonecode' => '+1-684'],
            ['id' => 146, 'code' => 'GU','name' => 'Guam', 'currency' => 'USD', 'phonecode' => '+1-671'],
            ['id' => 147, 'code' => 'MP','name' => 'Nördliche Marianen', 'currency' => 'USD', 'phonecode' => '+1-670'],
            ['id' => 148, 'code' => 'AX','name' => 'Ålandinseln', 'currency' => 'EUR', 'phonecode' => '+358'],
            ['id' => 149, 'code' => 'BL','name' => 'Saint-Barthélemy', 'currency' => 'EUR', 'phonecode' => '+590'],
            ['id' => 150, 'code' => 'JE','name' => 'Jersey', 'currency' => 'GBP', 'phonecode' => '+44'],
            ['id' => 151, 'code' => 'GG','name' => 'Guernsey', 'currency' => 'GBP', 'phonecode' => '+44'],
            ['id' => 152, 'code' => 'IM','name' => 'Isle of Man', 'currency' => 'GBP', 'phonecode' => '+44'],
            ['id' => 153, 'code' => 'MF','name' => 'Saint-Martin', 'currency' => 'EUR', 'phonecode' => '+590'],
            ['id' => 154, 'code' => 'PM','name' => 'Saint-Pierre und Miquelon', 'currency' => 'EUR', 'phonecode' => '+508'],
            ['id' => 155, 'code' => 'SX','name' => 'Sint Maarten', 'currency' => 'ANG', 'phonecode' => '+1-721'],
            ['id' => 156, 'code' => 'SS','name' => 'Südsudan', 'currency' => 'SSP', 'phonecode' => '+211'],
            ['id' => 157, 'code' => 'EH','name' => 'Westsahara', 'currency' => 'MAD', 'phonecode' => '+212'],
            ['id' => 158, 'code' => 'BQ','name' => 'Bonaire, Sint Eustatius und Saba', 'currency' => 'USD', 'phonecode' => '+599'],
            ['id' => 159, 'code' => 'SH','name' => 'St. Helena', 'currency' => 'SHP', 'phonecode' => '+290'],
            ['id' => 160, 'code' => 'IO','name' => 'Britisches Territorium im Indischen Ozean', 'currency' => 'USD', 'phonecode' => '+246'],
            ['id' => 161, 'code' => 'FK','name' => 'Falklandinseln', 'currency' => 'FKP', 'phonecode' => '+500'],
            ['id' => 162, 'code' => 'TF','name' => 'Französische Süd- und Antarktisgebiete', 'currency' => 'EUR', 'phonecode' => '+'],
            ['id' => 163, 'code' => 'HM','name' => 'Heard- und McDonald-Inseln', 'currency' => 'AUD', 'phonecode' => '+'],
            ['id' => 164, 'code' => 'VG','name' => 'Britische Jungferninseln', 'currency' => 'USD', 'phonecode' => '+1-284'],
            ['id' => 165, 'code' => 'VI','name' => 'Amerikanische Jungferninseln', 'currency' => 'USD', 'phonecode' => '+1-340'],
            ['id' => 166, 'code' => 'PN','name' => 'Pitcairninseln', 'currency' => 'NZD', 'phonecode' => '+870'],
            ['id' => 167, 'code' => 'WF','name' => 'Wallis und Futuna', 'currency' => 'XPF', 'phonecode' => '+681'],
            ['id' => 168, 'code' => 'CX','name' => 'Weihnachtsinsel', 'currency' => 'AUD', 'phonecode' => '+61'],
            ['id' => 169, 'code' => 'CC','name' => 'Kokosinseln', 'currency' => 'AUD', 'phonecode' => '+61'],
            ['id' => 170, 'code' => 'UM','name' => 'United States Minor Outlying Islands', 'currency' => 'USD', 'phonecode' => '+1'],
            ['id' => 171, 'code' => 'NF','name' => 'Norfolkinsel', 'currency' => 'AUD', 'phonecode' => '+672'],
            ['id' => 172, 'code' => 'MS','name' => 'Montserrat', 'currency' => 'XCD', 'phonecode' => '+1-664'],
            ['id' => 173, 'code' => 'TC','name' => 'Turks- und Caicosinseln', 'currency' => 'USD', 'phonecode' => '+1-649'],
            ['id' => 174, 'code' => 'PR','name' => 'Puerto Rico', 'currency' => 'USD', 'phonecode' => '+1-787'],
            ['id' => 175, 'code' => 'TA','name' => 'Tristan da Cunha', 'currency' => 'GBP', 'phonecode' => '+290']

        ];

        Country::insert($countries);
    }
}
